language: elixir
sudo: required
addons:
  chrome: stable
  postgresql: "9.6"
elixir: "1.6.0"
otp_release: "20.1"
services:
  - postgresql
before_install:
  - wget http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
script:
  - mix format --check-formatted mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs}"
  - mix test
  - mix credo --strict
